language: ruby

rvm:
  - 1.9.3

install: true


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./scripts/run_sc_server_master.sh 
  - sleep 5 # give sc-server some time to start

script: phantomjs phantomjs/test_runner.js --no-experimental --exclude-targets=/sproutcore/greenhouse

#build_image: shippable/minv2:beta



notifications:
  email: flase
#cache: true 
